### ISSUE TITLE
Object-Oriented API on top of UWG to accept inputs from many sources

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/urbanWeatherGen#2]
From @chriswmackey: 
"...improve the methods for inputting variables into the engine.  In particular, I think that building an object-oriented API on top of the engine will make it easier to accept inputs from many sources - whether they are XML files, JSON files, Excel interfaces, or Grasshopper components that assemble python objects to go directly into the engine."

@chriswmackey, Does this mean you're intending on creating a "core" dragonfly class that uses (for example) pyeuclid.py for geometry operations and then a separate class/repo of dragonfly_grasshopper / dragonfly_dynamo etc?

**Comment by chriswmackey** [comment]
@saeranv ,
Sorry for the late reply here.
To give you a sense of what I am thinking, I plan to develop most of this API under the Dragonfly umbrella and I have the meager-est start to it here:
https://github.com/chriswmackey/Dragonfly/tree/master/dragonfly

I am going to use a lot of the same structure that [butterfly](https://github.com/ladybug-tools/butterfly) uses and I am not going to use any external libraries like pyeuclid to do the geometry calculations.  Any geometry stuff is either going to be computed in Rhino (or other interfaces), with raw math, or we might even say that a lot of the core objects have no geometry since, at the end of the day, the UWG only takes three key geometry variables as input:
Average Building Height
Site Coverage Ratio
Facade to Site Ratio

I am thinking to eventually make classes for the following objects:
Building Typology
UWG Building (which have typologies and geometry parameters assigned to them)
UWG City
UWG Vegetation (used to represent grass or trees)
UWG Material
UWG Construction
UWG Schedule

This said, I don't think we can get around to any of this until we first get a working translation up and running.

**Comment by saeranv** [comment]
@chriswmackey cool. Just to make sure I understand - you already have code written up for most of this, in some form as gh components, correct? 

So, the plan is to rewrite them as proper classes and call the classes in new gh components? That seems straightforward.

**Comment by chriswmackey** [comment]
@saeranv ,
The code in the current GH components really is not worth keeping for the long run.  While it shows the proof of concept, it's not object oriented and it is not organized the way that it should be.
I'm planning to rewrite everything to generate actual python objects (instead of xml strings) and this will make it easier to accept input from different sources, including grasshopper, dynamo, or other interfaces.

**Comment by saeranv** [comment]
Done (on the UWG side)!
