### ISSUE TITLE
Bug in write_epw that Fails to Write Integer Wind Values

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/urbanWeatherGen#52]
@saeranv 
There seems to be a bug in the write_epw method of the [UWG (line 778)](https://github.com/ladybug-tools/urbanWeatherGen/blob/master/UWG/UWG.py#L778). The wind data in the weather file needs to be converted to a float in the event that it gets interpreted as an integer.  Once I cast the wind value to a float, everything worked like a charm.

**Comment by saeranv** [comment]
@chriswmackey that's weird, because I'm casting all the weather data to floats, and so there's no reason why it should think this is an integer. 

I wonder if the issue is related to this 661 UWG.py line:
```
 self.forc.wind = max(self.forcIP.wind[self.ceil_time_step], self.geoParam.windMin) # wind speed (m s-1)
```
When you define the minimum wind speed parameter (programmatically in Dragonfly via Grasshopper) - is the input a float or an integer. It should be float. 

Actually, this is something I should have mentioned before,, all the input parameters you are manually inputting (including the windMin parameter) must be floats. When I made the "API" for UWG, I assumed all inputs were floats and didn't explicitly cast anything. In the latest version of UWG. 

In the latest version of UWG, it will throw an error if it encounters an integer for any input parameters inserted via the API. The parameters in the initailize.uwg file I cast to floats while converting to string so it isn't a problem there.  

So try running this again with the latest UWG and see if it passes that test.  And If not can you send me the epw file and I'll check it out further. I'm a little wary of integers since it can mess up a lot of upstream calculations!

**Comment by chriswmackey** [comment]
@saeranv ,
Ah. Makes sense.  Yes, I was inputting the minimum wind as an integer.  Ok.  I have changed all of the default inputs to be floats with this commit:
https://github.com/chriswmackey/Dragonfly/commit/4de65e2da5bb85e28b079b5e4707de3f45940bf7#diff-1c398502f6766062cf35516df227dbdb
If you want to revert my previous commit and just put in a check to see whether the inputs are floats, that seems good.
