### ISSUE TITLE
Put line breaks into the progress bar?

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/urbanWeatherGen#53]
@saeranv ,
Do you know if it is possible to input line breaks in the progress bar output?  Without the breaks, it creates something that looks a little strange on the Grasshopper component:
![image](https://user-images.githubusercontent.com/5567574/40889934-953395be-673c-11e8-95ad-66e150f44431.png)
With some line breaks, I imagine that it will look consistently like this:
![image](https://user-images.githubusercontent.com/5567574/40889948-abbd68be-673c-11e8-8035-5127c5ba0e94.png)

**Comment by saeranv** [comment]
Oh man, I forgot the stdout stream won't translate to the readMe output. What I wanted to do eventually is add all the building energy updates that was in the original UWG code, so that you can track the specific simulation steps and progress. But for now I think I should just comment this out since it doesn't give any useful information.

**Comment by saeranv** [comment]
Fixed with #54 !

@chriswmackey  let me know if there's any other confusing output on the GH end.
